GRANT ALL PRIVILEGES on DATABASE reaction_bot to reaction_bot;
GRANT ALL PRIVILEGES on TABLE tbl_users_info to reaction_bot;
GRANT ALL PRIVILEGES on TABLE tbl_rule_interruptions to reaction_bot;
GRANT ALL PRIVILEGES on SEQUENCE tbl_users_info_user_id_seq to reaction_bot;
GRANT ALL PRIVILEGES on SEQUENCE tbl_rule_interruptions_rule_interruption_id_seq to reaction_bot;
GRANT ALL PRIVILEGES on TABLE tbl_room_settings to reaction_bot;
GRANT ALL PRIVILEGES on SEQUENCE tbl_room_settings_room_setting_id_seq to reaction_bot;
GRANT ALL PRIVILEGES on TABLE tbl_global_settings to reaction_bot;
GRANT ALL PRIVILEGES on SEQUENCE tbl_global_settings_global_setting_id_seq to reaction_bot;
